export const DATA_SOURCE = 'DATA_SOURCE';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const USER_SERVICE = 'USER_SERVICE';
export const JWT_OPTIONS = 'JWT_OPTIONS';
export const MAIL_OPTIONS = `MAIL_OPTIONS`;
export const VERIFICATION_REPOSITORY = 'VERIFICATION_REPOSITORY';
export const TOKEN_REPOSITORY = 'TOKEN_REPOSITORY';
