name: deploy

on:
  push:
    branches: ["develop"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: '18'
      - name: execute remote ssh & deploy backend server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            cd ~/goraeph_deploy/goraeph_back
            sudo git config --global --add safe.directory /home/***/goraeph_deploy/goraeph_back
            sudo git checkout develop
            sudo git pull
            sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
            sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            sudo npm -v

