name: deploy

on:
  push:
    branches: ['develop']
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: execute remote ssh & deploy backend server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SSH_HOST }}
          username: ${{ secrets.REMOTE_SSH_USERNAME }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            whoami
            cd ~/goraeph_deploy/goraeph_back
            sudo git config --global --add safe.directory /home/***/goraeph_deploy/goraeph_back
            sudo git pull
            sudo npm ci
            sudo npm run build
            sudo node ./dist/main.js
